version: 2.1
orbs:
  android: circleci/android@2.0.3
jobs:
  build-apk:
    machine:
      image: android:2024.11.1
    steps:
      - checkout
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: apk
workflows:
  build-apk-workflow:
    jobs:
      - build-apk